[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/*"
  status = 200